name: buildCSharpSDK

on:
  push:
    branches: [ main ]

jobs:
  Merge_WindowsPackages:
    name: "Merge x86 and x64 nuget packages for windows"
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
      

      - name: unzip artifacts
        run: |
          Expand-Archive CSharp_Windows32.zip -DestinationPath x86
          Expand-Archive CSharp_Windows64.zip -DestinationPath x64
          
          Expand-Archive x86\*.nupkg -DestinationPath x86\package
          Expand-Archive x64\*.nupkg -DestinationPath x64\package
          ls -R

      - name: merge x86 into x64
        run: |
          cp x64\package x64x86 -r
          mv x64x86\lib x64x86\build

          mkdir x64x86\build\netstandard2.0\x64
          mkdir x64x86\build\net45\x64
          mkdir x64x86\build\netstandard2.0\x86
          mkdir x64x86\build\net45\x86

          mv x64x86\build\netstandard2.0\*.dll x64x86\build\netstandard2.0\x64
          mv x64x86\build\net45\*.dll x64x86\build\net45\x64 

          mv x86\package\lib\netstandard2.0\* x64x86\build\netstandard2.0\x86
          mv x86\package\lib\net45\* x64x86\build\net45\x86


          cp csharp\OpenStudio.targets x64x86\build\netstandard2.0\
          cp csharp\OpenStudio.targets x64x86\build\net45\
          cd x64x86
          ls -R

      - name: make a new nupkg for Windows 
        run: |
          $VERSION = (Get-Item x64x86\build\netstandard2.0\x64\OpenStudio.dll).VersionInfo.FileVersion
          echo $VERSION
          Compress-Archive -U -Path x64x86\* -DestinationPath OpenStudio.$VERSION.nupkg
          cp *.nupkg x64x86\OpenStudio.nupkg
          ls

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nugetPackage
          path: x64x86\OpenStudio.nupkg

      - name: Tests on Windows
        run: |
          cd csharp/examples/OpenStudio.Tests/
          dotnet remove package OpenStudio 
          dotnet restore OpenStudio.Tests.csproj
          dotnet add OpenStudio.Tests.csproj package OpenStudio -s "./../../../"


          dotnet test OpenStudio.Tests.csproj /p:Platform=x64
          dotnet clean
          dotnet test OpenStudio.Tests.csproj /p:Platform=x86
          


