name: buildCSharpSDK

on:
  push:
    branches: [ main ]

jobs:
  Merge_WindowsPackages:
    name: "Merge x86 and x64 nuget packages for windows"
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
      

      - name: unzip artifacts
        run: |
          Expand-Archive CSharp_Windows32.zip -DestinationPath x86
          ls -R
          $Found = Get-ChildItem -Filter ("x86\*.nupkg")
          foreach ($entry in $Found){
            Rename-Item -Path $entry.FullName -NewName ($entry.Name.Replace('.nupkg','.zip'))
          }

          cd x86
          Expand-Archive *.zip -DestinationPath x86
          ls
      

      

