name: buildCSharpSDK

on:
  push:
    branches: [ main ]

jobs:
  Merge_WindowsPackages:
    name: "Merge x86 and x64 nuget packages for windows"
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
      

      - name: unzip artifacts
        run: |
          Expand-Archive CSharp_Windows32.zip -DestinationPath x86
          Expand-Archive CSharp_Windows64.zip -DestinationPath x64
          
          Expand-Archive x86\*.nupkg -DestinationPath x86\package
          Expand-Archive x64\*.nupkg -DestinationPath x64\package
          ls -R

      - name: merge
        run: |
          mv x64\package\lib\netstandard2.0\OpenStudio.txt x64\package\lib\netstandard2.0\x64\OpenStudio.txt 
          mv x64\package\lib\net45\OpenStudio.txt x64\package\lib\net45\x64\OpenStudio.txt 
          mv x86\package\lib\netstandard2.0\OpenStudio.txt x86\package\lib\netstandard2.0\x86\OpenStudio.txt 
          mv x86\package\lib\net45\OpenStudio.txt x86\package\lib\net45\x86\OpenStudio.txt 

          mv x64\package\lib x64\package\build
          mv x86\package\lib\netstandard2.0\x86 x64\package\build\netstandard2.0\x86
          mv x86\package\lib\net45\x86 x64\package\build\net45\x86

          cd x64\package\build
          ls -R



      

      

